name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm --prefix "functions" install
      - name: Yarn Add TSLint
        run: yarn global add tslint typescript
      - name: Lint
        run: npm --prefix "functions" run lint
      - name: Build
        run: npm --prefix "functions" run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: lib
          path: functions/lib
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: lib
          path: functions/lib
      - name: Install Dependencies
        run: npm --prefix "functions" install
      - name: Yarn Add TSLint
        run: yarn global add tslint typescript
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
